/**:
  ros__parameters:
    enable_delay_compensation: true
    prediction_time_horizon: 5.0
    # prediction_time_horizon: 7.8
    prediction_sampling_delta_time: 0.1
    min_velocity_for_map_based_prediction: 1.39
    min_crosswalk_user_velocity: 1.39
    dist_threshold_for_searching_lanelet: 3.0
    delta_yaw_threshold_for_searching_lanelet: 0.785
    sigma_lateral_offset: 0.5
    sigma_yaw_angle_deg: 5.0
    object_buffer_time_length: 2.0
    history_time_length: 1.0

    lane_change_detection:
      method: lat_diff_distance
      time_to_change_lane:
        dist_threshold_for_lane_change_detection: 1.0
        time_threshold_for_lane_change_detection: 5.0
        cutoff_freq_of_velocity_for_lane_change_detection: 0.1
      lat_diff_distance:
        dist_ratio_threshold_to_left_bound: -0.5
        dist_ratio_threshold_to_right_bound: 0.5
        diff_dist_threshold_to_left_bound: 0.29
        diff_dist_threshold_to_right_bound: -0.29
      num_continuous_state_transition: 3

    reference_path_resolution: 0.5
    prediction_time_horizon_rate_for_validate_lane_length: 0.8
    
    image_size: 39
    ViewLength: 27
    map_to_image_rate: 3.0
    lanelet_search_amount: 20
