/**:
ros__parameters:
  lanelet2_map_projector_type: UTM           # Options: MGRS, UTM, local
  latitude: '48.262685577935336'             # Latitude of map_origin, using in UTM
  longitude: '11.6639997281684'                # Longitude of map_origin, using in UTM

  center_line_resolution: 5.0                 # [m]
